baseURL = "https://www.concurrent.work"
languageCode = "en-us"
defaultContentLanguage = "en"
author = "Dongfang Qu"
title = "Concurrent Work"
theme = "hugo-vitae"
paginate = 5
enableRobotsTXT = true

copyright = "©Copyright | [Concurrent work](https://github.com/qudongfang/)"

pygmentsstyle = "colorful"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = ""

[taxonomies]
	tag = "tags"
	category = "categories"
	series = "series"

[params]
	# Use homepage.md instead of a list of posts
	homepage = false

	# Add meta keywords in head part (Site Keywords or Tags of Page)
	keywords = ["linux","SRE","golang","python"]

	# Add meta description in head part
	description = "Rambling of a coder who craves for knowledge and understanding of the world"

	# Add pagetitle to homepage <title> tag
	pagetitle = "All about static site generation"

	# Add a subtitle to your website
	subtitle = "Rambling of a coder who craves for knowledge and understanding of the world."

	# Activate to show authors on pages if available
	listAuthor = true

	# Add math typesetting with KaTeX (Global with this Param)
	math = true

	# Optional 80x80 avatar image.
    #avatar = "https://en.wikipedia.org/wiki/R2-D2#/media/File:R2-D2_Droid.png"

	# Optional favicons for website
	#favicon = true

	# Add list of sections that should show up on the homepage
        mainSections = ["posts"]

	# Add list of Sections/Types that should no be considered by RSS
	#nofeedSections = ["post"]

	# Deactivate Taxonomies for specific page types
	#disableTaxoTypes = [""]

	# Custom CSS applied to default styles. (Path could be "static/css/")
	#customCSS = "css/custom.css"

# Comments
[params.comments]
# Enable Comments with "true"
enabled = false

# Comment provider:
#   disqus (https://disqus.com)
#   commento (https://commento.io)
#engine = "disqus"

# Content types to disable comments on.
#disableOnTypes = ["page"]

[params.comments.disqus]
#shortname = "" # Paste the shortname from your Disqus dashboard.

[params.comments.commento]
#host = "" # Paste the domain of you commento.io system

# Navigation
[[menu.main]]
name = "All Posts"
url = "/posts"
weight = 1

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

# Social Menu
[[params.social]]
name = "Github"
icon = "fab fa-github"
url = "https://github.com/qudongfang"

[[params.social]]
name = "LinkedIn"
icon = "fab fa-linkedin"
url = "https://www.linkedin.com/in/qudongfang/"

[[params.social]]
name = "Twitter"
icon = "fab fa-twitter"
url = "https://twitter.com/qudongfang"
